{% set name = "espei" %}
{% set version = "0.8.9" %}
{% set sha256 = "4635cdd9ba80e0cd74f3696f7eb2ebeed8cfcf8c981fb0b08f3452edcaef2927" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - espei = espei.espei_script:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python >=3.7
    - cerberus
    - corner
    - dask >=2
    - distributed >=2
    - emcee <3
    - importlib_metadata
    - matplotlib-base
    - numpy >=1.20
    - pycalphad >=0.10.1
    - pydantic
    - python-symengine >=0.9
    - pyyaml
    - setuptools_scm >=6.0
    - scikit-learn >=1.0
    - scipy
    - tinydb >=4

test:
  imports:
    - espei
    - espei.core_utils
    - espei.datasets
    - espei.espei_script
    - espei.optimizers
    - espei.logger
    - espei.paramselect
    - espei.plot
    - espei.refdata
    - espei.rstate
    - espei.utils
    - pycalphad
  commands:
    - pip check
    - espei -h
    - espei --version
  requires:
    - pip

about:
  home: http://espei.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fitting thermodynamic models with pycalphad.
  description: |
    ESPEI, or Extensible Self-optimizing Phase Equilibria Infrastructure,
    is a tool for automated thermodynamic database development within the
    CALPHAD method.
  doc_url: http://espei.org
  dev_url: https://github.com/PhasesResearchLab/espei

extra:
  recipe-maintainers:
    - bocklund
    - richardotis
