{% set name = "espei" %}
{% set version = "0.7.6" %}
{% set sha256 = "371338f1dfea6bd5022ff0df96793962b316a2e21879319badeafe6e60c05c86" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - espei = espei.espei_script:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python >=3.6
    - numpy
    - scipy
    - sympy >=1.3
    - six
    - dask >=2
    - distributed >=2
    - tinydb >=3.8
    - scikit-learn
    - emcee <3
    - pycalphad >=0.8.2
    - pyyaml
    - cerberus
    - bibtexparser

test:
  imports:
    - espei
    - espei.core_utils
    - espei.datasets
    - espei.espei_script
    - espei.mcmc
    - espei.optimizers
    - espei.paramselect
    - espei.plot
    - espei.refdata
    - espei.rstate
    - espei.utils
    - pycalphad
  commands:
    - espei -h
    - espei --version

about:
  home: http://espei.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fitting thermodynamic models with pycalphad.
  description: |
    ESPEI, or Extensible Self-optimizing Phase Equilibria Infrastructure,
    is a tool for automated thermodynamic database development within the
    CALPHAD method.
  doc_url: http://espei.org
  dev_url: https://github.com/PhasesResearchLab/espei

extra:
  recipe-maintainers:
    - bocklund
    - richardotis
