{% set name = "espei" %}
{% set version = "0.7.11" %}
{% set sha256 = "fc069a321f08f914bfb001cee1cb38d1d1e2b36adb1ee2f2452d588c8c57d452" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  entry_points:
    - espei = espei.espei_script:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python >=3.6
    - bibtexparser
    - cerberus
    - corner
    - dask >=2
    - distributed >=2
    - emcee <3
    - matplotlib-base
    - numpy
    - pycalphad >=0.8.4
    - python-symengine
    - pyyaml
    - scikit-learn
    - scipy
    - sympy >=1.5.1
    - tinydb >=4

test:
  imports:
    - espei
    - espei.core_utils
    - espei.datasets
    - espei.espei_script
    - espei.mcmc
    - espei.optimizers
    - espei.paramselect
    - espei.plot
    - espei.refdata
    - espei.rstate
    - espei.utils
    - pycalphad
  commands:
    - espei -h
    - espei --version

about:
  home: http://espei.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fitting thermodynamic models with pycalphad.
  description: |
    ESPEI, or Extensible Self-optimizing Phase Equilibria Infrastructure,
    is a tool for automated thermodynamic database development within the
    CALPHAD method.
  doc_url: http://espei.org
  dev_url: https://github.com/PhasesResearchLab/espei

extra:
  recipe-maintainers:
    - bocklund
    - richardotis
